# Generated by Django 2.2.15 on 2021-01-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_item_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='content',
            field=models.TextField(),
        ),
    ]
