# Generated by Django 2.2.15 on 2020-12-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
            ],
        ),
    ]
