# Generated by Django 2.2.15 on 2020-12-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(default=2000),
            preserve_default=False,
        ),
    ]
