# Generated by Django 2.2.15 on 2021-01-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_auto_20210106_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
    ]
